run:
  name: "wan720720"
  output_root: "/ML-vePFS/research_gen/tja/test_infra_worldscore/output/wan720720"
  mode: eval-only
env:
  worldscore_path: "/ML-vePFS/research_gen/tja"
  data_path: "/ML-vePFS/research_gen/tja/WorldScore/data"
  diffsynth_env: "diffsynth"
  worldscore_env: "/ML-vePFS/research_gen/jmy/jmy_ws/envs_conda/worldscore6"

wan:
  checkpoint_path: "/ML-vePFS/research_gen/jmy/my/videox-fun-sft/output/wan2.1_camera_control-1.3b_runway_720720_crop/checkpoint-3080/transformer/diffusion_pytorch_model.safetensors"
  base_model_root: "/ML-vePFS/research_gen/WorldScore/WorldScore/models"
  negative_prompt: "色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走"
  cfg_scale: 6
  seed: 0
  sample_steps: 50
  fps: 16
  frames: 81
  resolution: [720, 720]

worldscore:
  model_name: "wan720720"
  runs_root_base: "/ML-vePFS/research_gen/tja/test_infra_worldscore/output"
  output_dir: "worldscore_output"
  sampled_json_path: "/ML-vePFS/research_gen/tja/WorldScore/data/sampled_worldscore.json"
  visual_movement: ["static", "dynamic"]
  config_overrides:
    frames: 81
    fps: 16
    resolution: [720, 720]
    focal_length: 500

filters:
  enable: false
  visual_movement: []
  visual_style: []
  scene_type: []
  category: []
  motion_type: []
  instance: []
  image_name: []
  image_contains: []
  camera_path_any: []

metrics:
  aspects: []
  metrics: []

compute:
  num_gpus: 8
  infer_use_dp: true
  eval_num_jobs: 8
  eval_use_slurm: false
  slurm_params: {}
